# Generated by Django 2.2.7 on 2019-11-14 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.TimeField()),
                ('time_closed', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Pet_Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('details', models.TextField()),
                ('date_time_added', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('details', models.TextField()),
                ('nickname', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('gender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='profiles.Gender')),
                ('pet_photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='profiles.Pet_Photo')),
            ],
        ),
        migrations.CreateModel(
            name='User_Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('details', models.TextField()),
                ('date_time_added', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photos', to='profiles.User_Account')),
            ],
        ),
        migrations.AddField(
            model_name='pet_photo',
            name='user_account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_photos', to='profiles.User_Account'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_joined', models.TimeField()),
                ('time_left', models.TimeField()),
                ('coversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='profiles.Conversation')),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='profiles.User_Account')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('time_stamp', models.TimeField()),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='profiles.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Interested_In_Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_in_genders', to='profiles.Gender')),
                ('user_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_in_genders', to='profiles.User_Account')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='profiles.User_Account'),
        ),
    ]
