# Generated by Django 2.2.7 on 2019-11-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='pet_photo_id',
        ),
    ]
