# Generated by Django 2.2.7 on 2019-11-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_user_account_pet_photo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interested_in_gender',
            name='gender_id',
        ),
        migrations.RemoveField(
            model_name='interested_in_gender',
            name='user_account_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='participant_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='coversation_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user_account_id',
        ),
        migrations.RemoveField(
            model_name='pet_photo',
            name='user_account_id',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='gender_id',
        ),
        migrations.RemoveField(
            model_name='user_photo',
            name='user_account_id',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Interested_In_Gender',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Pet_Photo',
        ),
        migrations.DeleteModel(
            name='User_Account',
        ),
        migrations.DeleteModel(
            name='User_Photo',
        ),
    ]
