# Generated by Django 2.2.7 on 2019-11-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_match_pet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='user_id',
            new_name='user',
        ),
    ]
